export const SideBarDataLinks = [
    {
        id: 0,
        name: 'INICIO ',
        path: '/',
        icon1: 'bi bi-house',
    },
    // {
    //     id: 1000,
    //     name: 'EXTRAS ',
    //     path: '/extras',
    //     icon1: 'bi bi-plus-square',
    // },
    // {
    //     id: 1001,
    //     name: 'TELEVISION ',
    //     path: '/television',
    //     icon1: 'bi bi-tv',
    // },


]

export const DiezDias = [
    {
        id: 1,
        name: 'DIA -> ',
        path: '/dia_uno',
        icon1: 'bi bi-0-square',
        icon2: 'bi bi-1-square',
    },
    {
        id: 2,
        name: 'DIA -> ',
        path: '/dia_dos',
        icon1: 'bi bi-0-square',
        icon2: 'bi bi-2-square',
    },
    {
        id: 3,
        name: 'DIA -> ',
        path: '/dia_tres',
        icon1: 'bi bi-0-square',
        icon2: 'bi bi-3-square',
    },
    {
        id: 4,
        name: 'DIA -> ',
        path: '/dia_cuatro',
        icon1: 'bi bi-0-square',
        icon2: 'bi bi-4-square',
    },
    {
        id: 5,
        name: 'DIA -> ',
        path: '/dia_cinco',
        icon1: 'bi bi-0-square',
        icon2: 'bi bi-5-square',
    },
    {
        id: 6,
        name: 'DIA -> ',
        path: '/dia_seis',
        icon1: 'bi bi-0-square',
        icon2: 'bi bi-6-square',
    },
    {
        id: 7,
        name: 'DIA -> ',
        path: '/dia_siete',
        icon1: 'bi bi-0-square',
        icon2: 'bi bi-7-square',
    },
    {
        id: 8,
        name: 'DIA -> ',
        path: '/dia_ocho',
        icon1: 'bi bi-0-square',
        icon2: 'bi bi-8-square',
    },
    {
        id: 9,
        name: 'DIA -> ',
        path: '/dia_nueve',
        icon1: 'bi bi-0-square',
        icon2: 'bi bi-9-square',
    },
    {
        id: 10,
        name: 'DIA -> ',
        path: '/dia_diez',
        icon1: 'bi bi-1-square',
        icon2: 'bi bi-0-square',
    },
]

export const VeinteDias = [
    {
        id: 11,
        name: 'DIA -> ',
        path: '/dia_11',
        icon1: 'bi bi-1-square',
        icon2: 'bi bi-1-square',
    },
    //{
    //    id: 12,
    //    name: 'DIA -> ',
    //    path: '/dia_12',
    //    icon1: 'bi bi-1-square',
    //    icon2: 'bi bi-2-square',
    //},
    // {
    //     id: 13,
    //     name: 'DIA -> ',
    //     path: '/dia_13',
    //     icon1: 'bi bi-1-square',
    //     icon2: 'bi bi-3-square',
    // },
    // {
    //     id: 14,
    //     name: 'DIA -> ',
    //     path: '/dia_14',
    //     icon1: 'bi bi-1-square',
    //     icon2: 'bi bi-4-square',
    // },
    // {
    //     id: 15,
    //     name: 'DIA -> ',
    //     path: '/dia_15',
    //     icon1: 'bi bi-1-square',
    //     icon2: 'bi bi-5-square',
    // },
    // {
    //     id: 16,
    //     name: 'DIA -> ',
    //     path: '/dia_16',
    //     icon1: 'bi bi-1-square',
    //     icon2: 'bi bi-6-square',
    // },
    // {
    //     id: 17,
    //     name: 'DIA -> ',
    //     path: '/dia_17',
    //     icon1: 'bi bi-1-square',
    //     icon2: 'bi bi-7-square',
    // },
    // {
    //     id: 18,
    //     name: 'DIA -> ',
    //     path: '/dia_18',
    //     icon1: 'bi bi-1-square',
    //     icon2: 'bi bi-8-square',
    // },
    // {
    //     id: 19,
    //     name: 'DIA -> ',
    //     path: '/dia_19',
    //     icon1: 'bi bi-1-square',
    //     icon2: 'bi bi-9-square',
    // },
    // {
    //     id: 20,
    //     name: 'DIA -> ',
    //     path: '/dia_20',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-0-square',
    // },
]
export const TreintaDias = [
    // {
    //     id: 21,
    //     name: 'DIA -> ',
    //     path: '/dia_21',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-1-square',
    // },
    // {
    //     id: 22,
    //     name: 'DIA -> ',
    //     path: '/dia_22',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-2-square',
    // },
    // {
    //     id: 23,
    //     name: 'DIA -> ',
    //     path: '/dia_23',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-3-square',
    // },
    // {
    //     id: 24,
    //     name: 'DIA -> ',
    //     path: '/dia_24',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-4-square',
    // },
    // {
    //     id: 25,
    //     name: 'DIA -> ',
    //     path: '/dia_25',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-5-square',
    // },
    // {
    //     id: 26,
    //     name: 'DIA -> ',
    //     path: '/dia_26',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-6-square',
    // },
    // {
    //     id: 27,
    //     name: 'DIA -> ',
    //     path: '/dia_27',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-7-square',
    // },
    // {
    //     id: 28,
    //     name: 'DIA -> ',
    //     path: '/dia_28',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-8-square',
    // },
    // {
    //     id: 29,
    //     name: 'DIA -> ',
    //     path: '/dia_29',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-9-square',
    // },
    // {
    //     id: 30,
    //     name: 'DIA -> ',
    //     path: '/dia_30',
    //     icon1: 'bi bi-3-square',
    //     icon2: 'bi bi-0-square',
    // },
]
export const CuarentaDias = [
    // {
    //     id: 31,
    //     name: 'DIA -> ',
    //     path: '/dia_31',
    //     icon1: 'bi bi-3-square',
    //     icon2: 'bi bi-1-square',
    // },
    // {
    //     id: 32,
    //     name: 'DIA -> ',
    //     path: '/dia_32',
    //     icon1: 'bi bi-3-square',
    //     icon2: 'bi bi-2-square',
    // },
    // {
    //     id: 33,
    //     name: 'DIA -> ',
    //     path: '/dia_33',
    //     icon1: 'bi bi-3-square',
    //     icon2: 'bi bi-3-square',
    // },
    // {
    //     id: 34,
    //     name: 'DIA -> ',
    //     path: '/dia_34',
    //     icon1: 'bi bi-3-square',
    //     icon2: 'bi bi-4-square',
    // },
    // {
    //     id: 35,
    //     name: 'DIA -> ',
    //     path: '/dia_35',
    //     icon1: 'bi bi-3-square',
    //     icon2: 'bi bi-5-square',
    // },
    // {
    //     id: 36,
    //     name: 'DIA -> ',
    //     path: '/dia_36',
    //     icon1: 'bi bi-3-square',
    //     icon2: 'bi bi-6-square',
    // },
    // {
    //     id: 37,
    //     name: 'DIA -> ',
    //     path: '/dia_37',
    //     icon1: 'bi bi-3-square',
    //     icon2: 'bi bi-7-square',
    // },
    // {
    //     id: 38,
    //     name: 'DIA -> ',
    //     path: '/dia_38',
    //     icon1: 'bi bi-3-square',
    //     icon2: 'bi bi-8-square',
    // },
    // {
    //     id: 39,
    //     name: 'DIA -> ',
    //     path: '/dia_39',
    //     icon1: 'bi bi-3-square',
    //     icon2: 'bi bi-9-square',
    // },
    // {
    //     id: 40,
    //     name: 'DIA -> ',
    //     path: '/dia_40',
    //     icon1: 'bi bi-4-square',
    //     icon2: 'bi bi-0-square',
    // },

]
export const CincuentaDias = [
    // {
    //     id: 41,
    //     name: 'DIA -> ',
    //     path: '/dia_41',
    //     icon1: 'bi bi-4-square',
    //     icon2: 'bi bi-1-square',
    // },
    // {
    //     id: 42,
    //     name: 'DIA -> ',
    //     path: '/dia_42',
    //     icon1: 'bi bi-4-square',
    //     icon2: 'bi bi-2-square',
    // },
    // {
    //     id: 43,
    //     name: 'DIA -> ',
    //     path: '/dia_43',
    //     icon1: 'bi bi-4-square',
    //     icon2: 'bi bi-3-square',
    // },
    // {
    //     id: 44,
    //     name: 'DIA -> ',
    //     path: '/dia_44',
    //     icon1: 'bi bi-4-square',
    //     icon2: 'bi bi-4-square',
    // },
    // {
    //     id: 45,
    //     name: 'DIA -> ',
    //     path: '/dia_45',
    //     icon1: 'bi bi-4-square',
    //     icon2: 'bi bi-5-square',
    // },
    // {
    //     id: 46,
    //     name: 'DIA -> ',
    //     path: '/dia_46',
    //     icon1: 'bi bi-4-square',
    //     icon2: 'bi bi-6-square',
    // },
    // {
    //     id: 47,
    //     name: 'DIA -> ',
    //     path: '/dia_47',
    //     icon1: 'bi bi-4-square',
    //     icon2: 'bi bi-7-square',
    // },
    // {
    //     id: 48,
    //     name: 'DIA -> ',
    //     path: '/dia_48',
    //     icon1: 'bi bi-4-square',
    //     icon2: 'bi bi-8-square',
    // },
    // {
    //     id: 49,
    //     name: 'DIA -> ',
    //     path: '/dia_49',
    //     icon1: 'bi bi-4-square',
    //     icon2: 'bi bi-9-square',
    // },
    // {
    //     id: 50,
    //     name: 'DIA -> ',
    //     path: '/dia_50',
    //     icon1: 'bi bi-5-square',
    //     icon2: 'bi bi-0-square',
    // },
]
