export const SideBarDataLinks = [
    {
        id: 0,
        name: 'INICIO ',
        path: '/',
        icon1: 'bi bi-house',
    },
    {
        id: 1000,
        name: 'EXTRAS ',
        path: '/extras',
        icon1: 'bi bi-plus-square',
    },
    {
        id: 1001,
        name: 'TELEVISION ',
        path: '/television',
        icon1: 'bi bi-tv',
    },
    {
        id: 1,
        name: 'DIA -> ',
        path: '/dia_uno',
        icon1: 'bi bi-0-square',
        icon2: 'bi bi-1-square',
    },
    {
        id: 2,
        name: 'DIA -> ',
        path: '/dia_dos',
        icon1: 'bi bi-0-square',
        icon2: 'bi bi-2-square',
    },
    {
        id: 3,
        name: 'DIA -> ',
        path: '/dia_tres',
        icon1: 'bi bi-0-square',
        icon2: 'bi bi-3-square',
    },
    {
        id: 4,
        name: 'DIA -> ',
        path: '/dia_cuatro',
        icon1: 'bi bi-0-square',
        icon2: 'bi bi-4-square',
    },
    // {
    //     id: 5,
    //     name: 'Dia 05',
    //     icon1: 'bi bi-0-square',
    //     icon2: 'bi bi-5-square',
    // },
    // {
    //     id: 6,
    //     name: 'Dia 06',
    //     icon1: 'bi bi-0-square',
    //     icon2: 'bi bi-6-square',
    // },
    // {
    //     id: 7,
    //     name: 'Dia 07',
    //     icon1: 'bi bi-0-square',
    //     icon2: 'bi bi-7-square',
    // },
    // {
    //     id: 8,
    //     name: 'Dia 08',
    //     icon1: 'bi bi-0-square',
    //     icon2: 'bi bi-8-square',
    // },
    // {
    //     id: 9,
    //     name: 'Dia 09',
    //     icon1: 'bi bi-0-square',
    //     icon2: 'bi bi-9-square',
    // },
    // {
    //     id: 10,
    //     name: 'Dia 10',
    //     icon1: 'bi bi-1-square',
    //     icon2: 'bi bi-0-square',
    // },
    // {
    //     id: 11,
    //     name: 'Dia 11',
    //     icon1: 'bi bi-1-square',
    //     icon2: 'bi bi-1-square',
    // },
    // {
    //     id: 12,
    //     name: 'Dia 12',
    //     icon1: 'bi bi-1-square',
    //     icon2: 'bi bi-2-square',
    // },
    // {
    //     id: 13,
    //     name: 'Dia 13',
    //     icon1: 'bi bi-1-square',
    //     icon2: 'bi bi-3-square',
    // },
    // {
    //     id: 14,
    //     name: 'Dia 14',
    //     icon1: 'bi bi-1-square',
    //     icon2: 'bi bi-4-square',
    // },
    // {
    //     id: 15,
    //     name: 'Dia 15',
    //     icon1: 'bi bi-1-square',
    //     icon2: 'bi bi-5-square',
    // },
    // {
    //     id: 16,
    //     name: 'Dia 16',
    //     icon1: 'bi bi-1-square',
    //     icon2: 'bi bi-6-square',
    // },
    // {
    //     id: 17,
    //     name: 'Dia 17',
    //     icon1: 'bi bi-1-square',
    //     icon2: 'bi bi-7-square',
    // },
    // {
    //     id: 18,
    //     name: 'Dia 18',
    //     icon1: 'bi bi-1-square',
    //     icon2: 'bi bi-8-square',
    // },
    // {
    //     id: 19,
    //     name: 'Dia 19',
    //     icon1: 'bi bi-1-square',
    //     icon2: 'bi bi-9-square',
    // },
    // {
    //     id: 20,
    //     name: 'Dia 20',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-0-square',
    // },
    // {
    //     id: 21,
    //     name: 'Dia 21',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-1-square',
    // },
    // {
    //     id: 22,
    //     name: 'Dia 22',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-2-square',
    // },
    // {
    //     id: 23,
    //     name: 'Dia 23',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-3-square',
    // },
    // {
    //     id: 24,
    //     name: 'Dia 24',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-4-square',
    // },
    // {
    //     id: 25,
    //     name: 'Dia 25',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-5-square',
    // },
    // {
    //     id: 26,
    //     name: 'Dia 26',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-6-square',
    // },
    // {
    //     id: 27,
    //     name: 'Dia 27',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-7-square',
    // },
    // {
    //     id: 28,
    //     name: 'Dia 28',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-8-square',
    // },
    // {
    //     id: 29,
    //     name: 'Dia 29',
    //     icon1: 'bi bi-2-square',
    //     icon2: 'bi bi-9-square',
    // },
    // {
    //     id: 30,
    //     name: 'Dia 30',
    //     icon1: 'bi bi-3-square',
    //     icon2: 'bi bi-0-square',
    // },



]
